version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: notes2notion-backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - BACKEND_PORT=5001
      - FLASK_ENV=development
      - ACCESS_CODE=${ACCESS_CODE}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock  # For MCP Docker access
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - notes2notion-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_HOST=${API_HOST:-localhost}
        - APP_ENV=${APP_ENV:-production}
    container_name: notes2notion-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_ENV=${APP_ENV:-production}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - notes2notion-network

networks:
  notes2notion-network:
    driver: bridge
